# Generated by Django 4.1.7 on 2023-03-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=('MALE', 'MALE'), max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.baseuser',),
        ),
        migrations.AddField(
            model_name='familymembermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='app.usermodel'),
        ),
    ]
